# config/services.yaml
parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'

# config/services.yaml
services:
    _defaults:
        autowire: true      # ativa a injeção automática
        autoconfigure: true # registra tags automaticamente
        bind:
            $uploadsDirectory: '%uploads_directory%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%uploads_directory%'

